import layout from '@/layout'

const RouteView = {
    name: 'RouteView',
    render: (h) => h('router-view')
}


export const asyncRouterMap = [
    {
        path:'/',
        component:layout,
        redirect: '/dashboard',
        children:[
            {
                path: '/dashboard',
                name: 'dashboard',
                component: ()=>import('@/views/dashboard/dashboard'),
                meta:{title:'主页',permission:["dashboard"],icon:'appstore'}
            },
            {
              path:'/auth',
              name:'auth',
              redirect:'/auth/user',
              component:RouteView,
              meta:{title:"权限管理",permission:['auth'],icon:"schedule"},
              children:[
                {
                  path:'/auth/role',
                  name:'role',
                  component:()=>import('@/views/auth/role'),
                  meta:{title:'角色管理',permission:['role'],parentPath:'auth'}
                },
                {
                  path:'/auth/user',
                  name:'user',
                  component:()=>import('@/views/auth/user'),
                  meta:{title:'用户管理',permission:['auth'],parentPath:'auth'}
                }
              ]
            },
            {
              path: '/audit',
              name: 'audit',
              component: ()=>import('@/views/audit/audit'),
              meta:{title:'审核管理',permission:["audit"],icon:'eye'}
            },
            {
              path:'/channel',
              name:'channel',
              redirect:'/channel/channel_admin',
              component:RouteView,
              meta:{title:"渠道管理",permission:['channelAdmin'],icon:"tags"},
              children:[
                {
                  path:'/channel/channel_admin',
                  name:'channel_admin',
                  component:()=>import('@/views/channel_admin/channelAdmin'),
                  meta:{title:'渠道管理员',permission:['channelAdmin'],parentPath:'channel'}
                },
                {
                  path:'/channel/channel_info',
                  name:'channel_info',
                  component:()=>import('@/views/channel_admin/channelInfo'),
                  meta:{title:'渠道信息',permission:['channelInfo'],parentPath:'channel'}
                }
              ]
            },
            {
                path:'/business',
                name:'business',
                redirect:'/business/business_admin',
                component:RouteView,
                meta:{title:'企业管理',permission:["business"],icon:'apartment'},
                children:[
                    {
                        path:'/business/business_admin',
                        name:'business_admin',
                        component:()=>import('@/views/business_admin/businessAdmin'),
                        meta:{title:'企业管理',permission:["business"],parentPath:'business'}
                    },
                    {
                        path:'/business/business_class',
                        name:'business_class',
                        component:()=>import('@/views/business_admin/businessClass'),
                        meta:{title:'企业部门',permission:["businessClass"],parentPath:'business'}
                    },
                    {
                        path:"/business/business_person",
                        name:"business_person",
                        component:()=>import('@/views/business_admin/businessPerson'),
                        meta:{title:'企业员工',permission:["businessPerson"],parentPath:'business'}
                    },
                    {
                        path:"/business/business_file",
                        name:"business_file",
                        component:()=>import('@/views/business_admin/businessFile'),
                        meta:{title:'企业空间文件',permission:["businessFile"],parentPath:'business'}
                    }
                ]
            },
            {
              path:'/fn',
              name:'fn',
              redirect:'/fn/fn_config',
              component:RouteView,
              meta:{title:"功能配置",permission:['fnConfig'],icon:"api"},
              children:[
                {
                  path:'/fn/fn_config',
                  name:'fn_config',
                  component:()=>import('@/views/fn/fnConfig'),
                  meta:{title:'配置管理',permission:['fnConfig'],parentPath:'fn'}
                },
                {
                  path:'/fn/shopping_mall',
                  name:'shopping_mall',
                  component:()=>import('@/views/fn/shoppingMall'),
                  meta:{title:'企业商城',permission:['shoppingMall'],parentPath:'fn'}
                },
                {
                  path:'/fn/contest',
                  name:'contest',
                  component:()=>import('@/views/fn/contest'),
                  meta:{title:'企业竞赛',permission:['contest'],parentPath:'fn'}
                }
              ]
            },
            {
              path:'/finance',
              name:'finance',
              redirect:'/finance/renewal_record',
              component:RouteView,
              meta:{title:"财务管理",permission:['renewalRecord'],icon:"account-book"},
              children:[
                {
                  path:'/finance/renewal_record',
                  name:'renewal_record',
                  component:()=>import('@/views/finance/renewalRecord'),
                  meta:{title:'企业续约记录',permission:['renewalRecord'],parentPath:'finance'}
                },
                {
                  path:'/finance/recharge_record',
                  name:'recharge_record',
                  component:()=>import('@/views/finance/rechargeRecord'),
                  meta:{title:'上格币充值记录',permission:['rechargeRecord'],parentPath:'finance'}
                },
                {
                  path:'/finance/buy_record',
                  name:'buy_record',
                  component:()=>import('@/views/finance/buyRecord'),
                  meta:{title:'课程购买记录',permission:['buyRecord'],parentPath:'finance'}
                }
              ]
            },
            {
              path:'/subject_admin',
              name:'subject_admin',
              component:RouteView,
              redirect:'/subject_admin/trades_class',
              meta:{title:'课程管理',permission:['tradesClass'],icon:'reconciliation'},
              children:[
                {
                  path:'/subject_admin/trades_class',
                  name:'trades_class',
                  component:()=>import('@/views/subject_admin/tradesClass'),
                  meta:{title:'行业类别',permission:['tradesClass'],parentPath:'subject_admin'}
                },
                {
                  path:'/subject_admin/subject_class',
                  name:'subject_class',
                  component:()=>import('@/views/subject_admin/subjectClass'),
                  meta:{title:'课程类别',permission:['subjectClass'],parentPath:'subject_admin'}
                },
                {
                  path:'/subject_admin/head_of_subject',
                  name:'head_of_subject',
                  component:()=>import('@/views/subject_admin/headOfSubject'),
                  meta:{title:'课程负责人',permission:['headOfSubject'],parentPath:'subject_admin'}
                },
                {
                  path:'/subject_admin/upload',
                  name:'uploadEdit',
                  component:()=>import('@/views/subject_admin/upload'),
                  meta:{title:'上传编辑',permission:['uploadEdit'],parentPath:'subject_admin'}
                }
              ]
            },
            {
              path:'/content',
              name:'content',
              component:RouteView,
              redirect:'/content/advert',
              meta:{title:'内容管理',permission:['advertAdmin'],icon:'container'},
              children:[
                {
                  path:'/content/advert',
                  name:'advert_admin',
                  component:()=>import('@/views/content/advert'),
                  meta:{title:'广告管理',permission:['advertAdmin'],parentPath:'content'}
                },
                {
                  path:'/content/level',
                  name:'level_admin',
                  component:()=>import('@/views/content/level'),
                  meta:{title:'等级头衔',permission:['levelAdmin'],parentPath:'content'}
                },
                {
                  path:'/content/news',
                  name:'news_admin',
                  component:()=>import('@/views/content/news'),
                  meta:{title:'咨询管理',permission:['newsAdmin'],parentPath:'content'}
                },
                {
                  path:'/content/FAQ',
                  name:'FAQ',
                  component:()=>import('@/views/content/FAQ'),
                  meta:{title:'FAQ管理',permission:['FAQ'],parentPath:'content'}
                },
                {
                  path:'/content/message',
                  name:'message_admin',
                  component:()=>import('@/views/content/message'),
                  meta:{title:'消息',permission:['messageAdmin'],parentPath:'content'}
                }
              ]
            },
            {
              path:'/documents',
              name:'documents',
              component:RouteView,
              redirect:'/documents/admin',
              meta:{title:'资料管理',permission:['documentsAdmin'],icon:'container'},
              children:[
                {
                  path:'/documents/class',
                  name:'documents_class',
                  component:()=>import('@/views/documents/documentsClass'),
                  meta:{title:'资料分类',permission:['documentsClass'],parentPath:'documents'}
                },
                {
                  path:'/documents/admin',
                  name:'documents_admin',
                  component:()=>import('@/views/documents/documentsAdmin'),
                  meta:{title:'资料管理',permission:['documentsAdmin'],parentPath:'documents'}
                }
              ]
            }
        ]
    },
    {
        path: '*', redirect: '/404', hidden: true
    }
]


export const constantRouterMap = [
    {
        path:'/login',
        name:'login',
        component:()=>import('@/views/user/login'),
        meta:{title:"登录"}
    },
    {
        path: '/404',
        component:()=>import('@/views/exception/404')
    }
]